### ISSUE TITLE
Q1 will stop IGN input from going high

### ISSUE THREAD

**Issue by EidoJ** [lukasloetkolben/OpenRelay#2]
I haven't looked at the project files, only the docs/OpenRelay.pdf schematic.
The inherent base-collector diode in the BJT will conduct to ground, causing the IGN input to not be allowed to go high.

**Comment by lukasloetkolben** [comment]
Sorry you are right, i will update it later!

**Comment by lukasloetkolben** [comment]
I'm a little confused.
SO2222 has a SOT-23 Footprint, but in the Documentation the pin-numbers do not match.
Can you have a look?

![sot23](https://user-images.githubusercontent.com/61192133/171024367-87994cc9-2e79-4db0-96f4-2b6bd633b4de.png)
![so2222](https://user-images.githubusercontent.com/61192133/171024373-d41e0896-9b19-4935-bda5-9fdb474b2811.png)

**Comment by EidoJ** [comment]
I don't have KiCAD on my phone at the moment. Perhaps the KiCAD schematic symbol feet numbers are also swapped to account for the mismatch.
Edit: I wasn't thinking straight. It looks like the schematic symbol does actually match the datasheet schematic symbol pin numbers, but the pin layout is different. You're probably better off going with a different transistor or MOSFET. What is this circuit trying to do?
